apiVersion: v1
kind: Service
metadata:
  name: {{ include "relay.fullname" . }}
  labels:
    {{- include "relay.labels" . | nindent 4 }}
    app.kubernetes.io/plane: inference
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "relay.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.inferencePort }}
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "relay.fullname" . }}-control
  labels:
    {{- include "relay.labels" . | nindent 4 }}
    app.kubernetes.io/plane: control
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "relay.selectorLabels" . | nindent 4 }}
  ports:
    - name: control
      port: {{ .Values.service.controlPort }}
      targetPort: control
      protocol: TCP
