apiVersion: relay.wyolet.dev/v1
kind: Model
metadata:
    name: ollama/llama2:70b
    labels:
        family: ollama/llama2:70b
        source: litellm
        source_version: "2026-05-13"
spec:
    provider: ollama
    upstreamName: ollama/llama2:70b
    family: ollama/llama2:70b
    capabilities:
        chat: true
        streaming: true
    modalities:
        input:
            - text
        output:
            - text
    contextWindowInput: 4096
    contextWindowOutput: 4096
    contextWindowTotal: 4096
