DROP TABLE IF EXISTS attachments;
DROP TABLE IF EXISTS rate_limits;
DROP TABLE IF EXISTS routes;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS secrets;
DROP TABLE IF EXISTS pools;
DROP TABLE IF EXISTS providers;
