DROP TRIGGER IF EXISTS providers_resource_version ON providers;
DROP TRIGGER IF EXISTS hosts_resource_version ON hosts;
DROP TRIGGER IF EXISTS models_resource_version ON models;
DROP TRIGGER IF EXISTS secrets_resource_version ON secrets;
DROP TRIGGER IF EXISTS rate_limits_resource_version ON rate_limits;
DROP TRIGGER IF EXISTS policies_resource_version ON policies;
DROP TRIGGER IF EXISTS pricings_resource_version ON pricings;
DROP TRIGGER IF EXISTS host_bindings_resource_version ON host_bindings;
DROP TRIGGER IF EXISTS relay_keys_resource_version ON relay_keys;
DROP TRIGGER IF EXISTS teams_resource_version ON teams;
DROP TRIGGER IF EXISTS projects_resource_version ON projects;
DROP TRIGGER IF EXISTS service_accounts_resource_version ON service_accounts;
DROP TRIGGER IF EXISTS groups_resource_version ON groups;
DROP TRIGGER IF EXISTS roles_resource_version ON roles;
DROP TRIGGER IF EXISTS role_bindings_resource_version ON role_bindings;
DROP TRIGGER IF EXISTS policy_bindings_resource_version ON policy_bindings;
DROP FUNCTION IF EXISTS bump_resource_version();

ALTER TABLE providers        DROP COLUMN IF EXISTS resource_version;
ALTER TABLE hosts            DROP COLUMN IF EXISTS resource_version;
ALTER TABLE models           DROP COLUMN IF EXISTS resource_version;
ALTER TABLE secrets          DROP COLUMN IF EXISTS resource_version;
ALTER TABLE rate_limits      DROP COLUMN IF EXISTS resource_version;
ALTER TABLE policies         DROP COLUMN IF EXISTS resource_version;
ALTER TABLE pricings         DROP COLUMN IF EXISTS resource_version;
ALTER TABLE host_bindings    DROP COLUMN IF EXISTS resource_version;
ALTER TABLE relay_keys       DROP COLUMN IF EXISTS resource_version;
ALTER TABLE teams            DROP COLUMN IF EXISTS resource_version;
ALTER TABLE projects         DROP COLUMN IF EXISTS resource_version;
ALTER TABLE service_accounts DROP COLUMN IF EXISTS resource_version;
ALTER TABLE groups           DROP COLUMN IF EXISTS resource_version;
ALTER TABLE roles            DROP COLUMN IF EXISTS resource_version;
ALTER TABLE role_bindings    DROP COLUMN IF EXISTS resource_version;
ALTER TABLE policy_bindings  DROP COLUMN IF EXISTS resource_version;
