apiVersion: relay.wyolet.dev/v1
kind: Model
metadata:
    name: ft:gpt-4.1-nano-2025-04-14
    labels:
        family: ft:gpt
        source: litellm
        source_version: "2026-05-07"
spec:
    provider: openai
    upstreamName: ft:gpt-4.1-nano-2025-04-14
    family: ft:gpt
    capabilities:
        chat: true
        streaming: true
        tools: true
        parallelTools: true
        promptCache: true
        structuredOutput: true
        systemMessages: true
    modalities:
        input:
            - text
        output:
            - text
    contextWindowInput: 1047576
    contextWindowOutput: 32768
    contextWindowTotal: 1047576
    pricing:
        currency: USD
        unit: per_million
        rates:
            tokens.batch_input: 0.09999999999999999
            tokens.batch_output: 0.39999999999999997
            tokens.cache_read: 0.049999999999999996
            tokens.input: 0.19999999999999998
            tokens.output: 0.7999999999999999
