// Package catalogvalidate is the cross-entity graph linter for the catalog
// repo's `data/` tree. It complements two existing layers:
//
//  1. Per-entity Validate() methods (struct shape + intra-entity rules).
//     These run during manifest.ToX translate or domain Validate() and only
//     see one entity at a time.
//
//  2. JSON Schema generated by huma (structural — required fields, types,
//     regex/length). Runs in editors and catalog CI via check-jsonschema.
//
// catalogvalidate fills the remaining gap: relational and graph-completeness
// checks across the whole catalog. Examples:
//
//   - policy.spec.hostKeys names a HostKey that doesn't exist
//   - hostkey.spec.policyId names a host-owned Policy whose owner is a
//     different host than hostkey.spec.hostId
//   - hostBinding.snapshots[] references a snapshot name not in
//     Model.spec.snapshots[]
//   - duplicate names within a kind
//   - (warn) Model with zero enabled host bindings — won't surface
//   - (warn) HostKey with no user-owned Policy listing it — relay can't
//     reach the underlying models
//
// The output is a list of Issues, never an early-fail. Catalog CI dumps all
// at once so authors fix everything in one pass instead of iteratively
// playing whack-a-mole.
//
// Operates on []manifest.Document so it works at catalog-time (names as
// refs, ids not yet minted). The seed loader can use the same package to
// gate writes; control-plane online edits log issues but don't block,
// matching the snapshot reconciler's forgiving semantics.
package catalogvalidate

import (
	"fmt"
	"sort"
	"strings"

	"github.com/wyolet/relay/app/manifest"
)

// Severity categorizes how seriously to treat an Issue.
type Severity int

const (
	// SeverityError is a graph-integrity problem the catalog cannot ship
	// with. Examples: unresolvable ref, duplicate name within a kind.
	SeverityError Severity = iota

	// SeverityWarning is a curation hint, not a correctness break. The
	// catalog will load and run, but something is probably misconfigured.
	// Examples: orphan models, dangling hostkeys.
	SeverityWarning
)

func (s Severity) String() string {
	switch s {
	case SeverityError:
		return "error"
	case SeverityWarning:
		return "warning"
	default:
		return "?"
	}
}

// IssueKind is a coarse-grained classification of what went wrong. The
// human Message field carries the specifics.
type IssueKind string

const (
	KindRefMissing      IssueKind = "ref_missing"
	KindOwnerMismatch   IssueKind = "owner_mismatch"
	KindSnapshotMissing IssueKind = "snapshot_missing"
	KindDuplicateName   IssueKind = "duplicate_name"
	KindOrphan          IssueKind = "orphan"
	KindIncomplete      IssueKind = "incomplete"
	KindInvariant       IssueKind = "invariant"
)

// Ref points at one location in the catalog: a kind + name, plus an
// optional field path for sub-locations.
type Ref struct {
	Kind  string
	Name  string
	Field string // optional, like "spec.hostKeys[2]"
}

func (r Ref) String() string {
	if r.Kind == "" && r.Name == "" {
		return ""
	}
	base := fmt.Sprintf("%s/%s", r.Kind, r.Name)
	if r.Field != "" {
		return base + "." + r.Field
	}
	return base
}

// Issue is one finding from the validator.
type Issue struct {
	Severity Severity
	Kind     IssueKind
	Source   Ref
	Target   Ref // optional — what the source was pointing at when it broke
	Message  string
}

// ValidateGraph runs every cross-entity check over docs and returns the
// findings, sorted deterministically (by severity then source). Empty slice
// means the catalog is graph-complete.
func ValidateGraph(docs []manifest.Document) []Issue {
	g := buildGraph(docs)

	var issues []Issue
	issues = append(issues, checkDuplicateNames(g)...)
	issues = append(issues, checkProviderRefs(g)...)
	issues = append(issues, checkHostRefs(g)...)
	issues = append(issues, checkModelRefs(g)...)
	issues = append(issues, checkHostKeyRefs(g)...)
	issues = append(issues, checkPolicyRefs(g)...)
	issues = append(issues, checkPricingRefs(g)...)
	issues = append(issues, checkRelayKeyRefs(g)...)
	issues = append(issues, checkOrphans(g)...)

	sortIssues(issues)
	return issues
}

// graph indexes docs by kind+name for O(1) ref lookup during checks.
// Slices of issues are intentionally separate from the lookup index so
// checks can be added without touching the indexing code.
type graph struct {
	Providers  map[string]*manifest.ProviderDTO
	Hosts      map[string]*manifest.HostDTO
	Models     map[string]*manifest.ModelDTO
	HostKeys   map[string]*manifest.HostKeyDTO
	Policies   map[string]*manifest.PolicyDTO
	RateLimits map[string]*manifest.RateLimitDTO
	RelayKeys  map[string]*manifest.RelayKeyDTO
	Pricings   map[string]*manifest.PricingDTO

	// duplicates tracks names that appeared more than once within a kind.
	// Each entry holds the kind + name; checkDuplicateNames emits issues.
	duplicates []Ref
}

func buildGraph(docs []manifest.Document) *graph {
	g := &graph{
		Providers:  map[string]*manifest.ProviderDTO{},
		Hosts:      map[string]*manifest.HostDTO{},
		Models:     map[string]*manifest.ModelDTO{},
		HostKeys:   map[string]*manifest.HostKeyDTO{},
		Policies:   map[string]*manifest.PolicyDTO{},
		RateLimits: map[string]*manifest.RateLimitDTO{},
		RelayKeys:  map[string]*manifest.RelayKeyDTO{},
		Pricings:   map[string]*manifest.PricingDTO{},
	}
	for i := range docs {
		d := &docs[i]
		switch {
		case d.Provider != nil:
			indexOne(g, "Provider", d.Provider.Metadata.Name, func() bool {
				_, dup := g.Providers[d.Provider.Metadata.Name]
				g.Providers[d.Provider.Metadata.Name] = d.Provider
				return dup
			})
		case d.Host != nil:
			indexOne(g, "Host", d.Host.Metadata.Name, func() bool {
				_, dup := g.Hosts[d.Host.Metadata.Name]
				g.Hosts[d.Host.Metadata.Name] = d.Host
				return dup
			})
		case d.Model != nil:
			indexOne(g, "Model", d.Model.Metadata.Name, func() bool {
				_, dup := g.Models[d.Model.Metadata.Name]
				g.Models[d.Model.Metadata.Name] = d.Model
				return dup
			})
		case d.HostKey != nil:
			indexOne(g, "HostKey", d.HostKey.Metadata.Name, func() bool {
				_, dup := g.HostKeys[d.HostKey.Metadata.Name]
				g.HostKeys[d.HostKey.Metadata.Name] = d.HostKey
				return dup
			})
		case d.Policy != nil:
			indexOne(g, "Policy", d.Policy.Metadata.Name, func() bool {
				_, dup := g.Policies[d.Policy.Metadata.Name]
				g.Policies[d.Policy.Metadata.Name] = d.Policy
				return dup
			})
		case d.RateLimit != nil:
			indexOne(g, "RateLimit", d.RateLimit.Metadata.Name, func() bool {
				_, dup := g.RateLimits[d.RateLimit.Metadata.Name]
				g.RateLimits[d.RateLimit.Metadata.Name] = d.RateLimit
				return dup
			})
		case d.RelayKey != nil:
			indexOne(g, "RelayKey", d.RelayKey.Metadata.Name, func() bool {
				_, dup := g.RelayKeys[d.RelayKey.Metadata.Name]
				g.RelayKeys[d.RelayKey.Metadata.Name] = d.RelayKey
				return dup
			})
		case d.Pricing != nil:
			indexOne(g, "Pricing", d.Pricing.Metadata.Name, func() bool {
				_, dup := g.Pricings[d.Pricing.Metadata.Name]
				g.Pricings[d.Pricing.Metadata.Name] = d.Pricing
				return dup
			})
		}
	}
	return g
}

func indexOne(g *graph, kind, name string, insertReportDup func() bool) {
	if name == "" {
		return
	}
	if insertReportDup() {
		g.duplicates = append(g.duplicates, Ref{Kind: kind, Name: name})
	}
}

// sortIssues orders findings by severity (errors first) then source.
func sortIssues(issues []Issue) {
	sort.SliceStable(issues, func(i, j int) bool {
		if issues[i].Severity != issues[j].Severity {
			return issues[i].Severity < issues[j].Severity
		}
		a, b := issues[i].Source.String(), issues[j].Source.String()
		if a != b {
			return a < b
		}
		return issues[i].Message < issues[j].Message
	})
}

// Format renders issues as a multi-line, human-readable report.
// CLI binaries can either use this or roll their own format.
func Format(issues []Issue) string {
	if len(issues) == 0 {
		return "catalog ok: 0 issues.\n"
	}
	var b strings.Builder
	errs, warns := 0, 0
	for _, is := range issues {
		switch is.Severity {
		case SeverityError:
			errs++
		case SeverityWarning:
			warns++
		}
		fmt.Fprintf(&b, "%s\t%s\t%s", is.Severity, is.Kind, is.Source)
		if is.Target.String() != "" {
			fmt.Fprintf(&b, " → %s", is.Target)
		}
		fmt.Fprintf(&b, "\t%s\n", is.Message)
	}
	fmt.Fprintf(&b, "\n%d errors, %d warnings.\n", errs, warns)
	return b.String()
}

// HasErrors reports whether any issue is a SeverityError.
func HasErrors(issues []Issue) bool {
	for _, is := range issues {
		if is.Severity == SeverityError {
			return true
		}
	}
	return false
}
