package catalog

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"encoding/json"
	"fmt"
	"io"
	"os"
)

//go:generate go run ../../cmd/catalog-embed -o catalog.json.gz

// catalog.json.gz is generated by cmd/catalog-embed (make catalog-embed).
// Shipped compressed so regenerations swap one small blob instead of a
// 25k-line JSON diff. Do not hand-edit; regenerate when the public
// catalog bumps.
//
//go:embed catalog.json.gz
var embedded []byte

// Load inflates and unmarshals the embedded catalog and builds
// resolution indexes.
func Load() (*IndexedCatalog, error) {
	gz, err := gzip.NewReader(bytes.NewReader(embedded))
	if err != nil {
		return nil, fmt.Errorf("catalog: inflate embedded: %w", err)
	}
	data, err := io.ReadAll(gz)
	if err != nil {
		return nil, fmt.Errorf("catalog: inflate embedded: %w", err)
	}
	var c Catalog
	if err := json.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("catalog: unmarshal embedded: %w", err)
	}
	return indexCatalog(&c)
}

// LoadBytes unmarshals catalog JSON and builds resolution indexes. The
// override seam for callers carrying their own catalog data.
func LoadBytes(data []byte) (*IndexedCatalog, error) {
	var c Catalog
	if err := json.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("catalog: unmarshal: %w", err)
	}
	return indexCatalog(&c)
}

// LoadFile loads a catalog from a local JSON file, transparently
// inflating gzip (as produced by catalog-embed -o *.gz). The lib never
// fetches anything — a newer or custom catalog is supplied by path, the
// embedded one is the shipped default.
func LoadFile(path string) (*IndexedCatalog, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("catalog: %w", err)
	}
	if len(data) > 1 && data[0] == 0x1f && data[1] == 0x8b { // gzip magic
		gz, err := gzip.NewReader(bytes.NewReader(data))
		if err != nil {
			return nil, fmt.Errorf("catalog: inflate %s: %w", path, err)
		}
		if data, err = io.ReadAll(gz); err != nil {
			return nil, fmt.Errorf("catalog: inflate %s: %w", path, err)
		}
	}
	return LoadBytes(data)
}
