package catalog

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

//go:generate go run ../../cmd/catalog-embed -o catalog.json

// catalog.json is generated by cmd/catalog-embed (make catalog-embed). Do not
// hand-edit; regenerate when the public catalog bumps.
//
//go:embed catalog.json
var embedded []byte

// Load unmarshals the embedded catalog and builds resolution indexes.
func Load() (*IndexedCatalog, error) {
	var c Catalog
	if err := json.Unmarshal(embedded, &c); err != nil {
		return nil, fmt.Errorf("catalog: unmarshal embedded: %w", err)
	}
	return indexCatalog(&c)
}

// LoadBytes unmarshals catalog JSON (for tests).
func LoadBytes(data []byte) (*IndexedCatalog, error) {
	var c Catalog
	if err := json.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("catalog: unmarshal: %w", err)
	}
	return indexCatalog(&c)
}
