// Package schemas embeds the generated JSON Schemas for the manifest kinds
// so the relay can serve them at /api/schemas/{version}/{kind}. The files
// are generated by cmd/catalog-schemas (`make schemas`); nothing here is
// hand-written.
package schemas

import "embed"

//go:embed v1alpha2/*.json
var FS embed.FS
