// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ParentKind    string `db:"parent_kind" json:"parent_kind"`
	ParentName    string `db:"parent_name" json:"parent_name"`
	RatelimitName string `db:"ratelimit_name" json:"ratelimit_name"`
	Meter         string `db:"meter" json:"meter"`
}

type Model struct {
	Name      string             `db:"name" json:"name"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	Spec      []byte             `db:"spec" json:"spec"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Pool struct {
	Name      string             `db:"name" json:"name"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	Spec      []byte             `db:"spec" json:"spec"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Provider struct {
	Name      string             `db:"name" json:"name"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	Spec      []byte             `db:"spec" json:"spec"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RateLimit struct {
	Name      string             `db:"name" json:"name"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	Spec      []byte             `db:"spec" json:"spec"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Route struct {
	Name      string             `db:"name" json:"name"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	Spec      []byte             `db:"spec" json:"spec"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Secret struct {
	Name      string             `db:"name" json:"name"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	Spec      []byte             `db:"spec" json:"spec"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
